runtime: go116
main: ./appengine

env_variables:
  GIN_MODE: "release"

includes:
  - secrets.yaml

handlers:
  - url: /.*
    script: auto
    secure: always
    login: admin

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  max_instances: 1
  min_pending_latency: 5000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80
